# Generated by Django 4.1.7 on 2023-03-03 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, verbose_name='Name')),
                ('category_description', models.TextField(verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('deleted_at', models.DateTimeField(auto_now_add=True, verbose_name='Deleted at')),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_name', models.CharField(max_length=50, verbose_name='Name')),
                ('gender_description', models.TextField(verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('deleted_at', models.DateTimeField(auto_now_add=True, verbose_name='Deleted at')),
            ],
            options={
                'verbose_name': 'Gender',
                'verbose_name_plural': 's',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='Name')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Price')),
                ('prodruct_description', models.TextField(verbose_name='Description')),
                ('SKU', models.CharField(max_length=50, verbose_name='SKU')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('deleted_at', models.DateTimeField(auto_now_add=True, verbose_name='Deleted at')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category', verbose_name='Category')),
                ('gender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gender', verbose_name='Gender')),
            ],
        ),
    ]
