# Generated by Django 4.1.7 on 2023-03-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gender',
            options={'verbose_name': 'Gender', 'verbose_name_plural': 'Genders'},
        ),
        migrations.AddField(
            model_name='product',
            name='mainproduct_image',
            field=models.ImageField(blank=True, height_field=1485, upload_to='main_image', verbose_name='Main Product Image', width_field=1200),
        ),
    ]
