# Generated by Django 4.1.7 on 2023-03-03 19:17

import autoslug.fields
import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_gender_options_product_mainproduct_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='product_name', slugify=core.models.Product.custom_slugify, unique_with=['id__id', 'created_at__month']),
        ),
        migrations.AlterField(
            model_name='product',
            name='mainproduct_image',
            field=models.ImageField(blank=True, upload_to='main_image', verbose_name='Main Product Image'),
        ),
    ]
